backbone:
  OS: 16
  bn_d: 0.05
  dropout: 0.02
  extra:
    shallow_feats: true
    width_mult: 1.0
  name: mobilenetv2
  train: true
dataset:
  color_map:
    0:
    - 0
    - 0
    - 0
    1:
    - 60
    - 20
    - 220
  img_means:
  - 0.47709312988745783
  - 0.4643970602527784
  - 0.4446694214593004
  img_prop:
    depth: 3
    height: 480
    width: 640
  img_stds:
  - 0.30698397568100977
  - 0.29866009782488506
  - 0.3047567782775573
  labels:
    0: background
    1: person
  labels_w:
    0: 1.0
    1: 1.0
  location: /media/oliver/Data/Ubuntu/mowro/datasets/person-ai/
  name: persons-mowro
  workers: 3
decoder:
  bn_d: 0.05
  dropout: 0.02
  extra:
    aspp_channels: 32
    last_channels: 16
  name: aspp_progressive
  train: true
head:
  dropout: 0.1
  name: segmentation
train:
  avg_N: 3
  batch_size: 12
  crop_prop:
    height: 480
    width: 480
  down_epochs: 30
  final_decay: 0.995
  loss: xentropy
  max_epochs: 300
  max_lr: 0.01
  max_momentum: 0.9
  min_lr: 0.001
  min_momentum: 0.85
  report_batch: 1
  report_epoch: 1
  save_imgs: true
  save_summary: true
  up_epochs: 0.5
  w_decay: 0.0005
